In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv(r'D:\Great learning\Datasets\Automobile.csv')

In [4]:
dataset.head()

,symboling,normalized_losses,make,fuel_type,aspiration,number_of_doors,body_style,drive_wheels,engine_location,wheel_base,...,engine_size,fuel_system,bore,stroke,compression_ratio,horsepower,peak_rpm,city_mpg,highway_mpg,price
0,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
1,3,168,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,16500
2,1,168,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,152,mpfi,2.68,3.47,9.0,154,5000,19,26,16500
3,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,109,mpfi,3.19,3.40,10.0,102,5500,24,30,13950
4,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,136,mpfi,3.19,3.40,8.0,115,5500,18,22,17450

In [6]:
dataset.describe().transpose()

,count,mean,std,min,25%,50%,75%,max
symboling,201.0,0.840796,1.254802,-2.00,0.00,1.00,2.00,3.00
normalized_losses,201.0,125.189055,33.572966,65.00,101.00,122.00,150.00,256.00
wheel_base,201.0,98.797015,6.066366,86.60,94.50,97.00,102.40,120.90
length,201.0,174.200995,12.322175,141.10,166.80,173.20,183.50,208.10
width,201.0,65.889055,2.101471,60.30,64.10,65.50,66.60,72.00
height,201.0,53.766667,2.447822,47.80,52.00,54.10,55.50,59.80
curb_weight,201.0,2555.666667,517.296727,1488.00,2169.00,2414.00,2926.00,4066.00
engine_size,201.0,126.875622,41.546834,61.00,98.00,120.00,141.00,326.00
bore,201.0,3.329701,0.268166,2.54,3.15,3.31,3.58,3.94
stroke,201.0,3.261741,0.317875,2.07,3.11,3.29,3.46,4.17
compression_ratio,201.0,10.164279,4.004965,7.00,8.60,9.00,9.40,23.00
horsepower,201.0,103.263682,37.389372,48.00,70.00,95.00,116.00,262.00
peak_rpm,201.0,5121.393035,479.624905,4150.00,4800.00,5200.00,5500.00,6600.00
city_mpg,201.0,25.179104,6.423220,13.00,19.00,24.00,30.00,49.00
highway_mpg,201.0,30.686567,6.815150,16.00,25.00,30.00,34.00,54.00
price,201.0,13207.129353,7947.066342,5118.00,7775.00,10295.00,16500.00,45400.00

In [10]:
horsepower = sorted(dataset.horsepower)

In [12]:
horsepower

[48,
 52,
 52,
 55,
 56,
 56,
 58,
 60,
 62,
 62,
 62,
 62,
 62,
 62,
 64,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 68,
 69,
 69,
 69,
 69,
 69,
 69,
 69,
 69,
 69,
 69,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 70,
 72,
 73,
 73,
 73,
 76,
 76,
 76,
 76,
 76,
 78,
 82,
 82,
 82,
 82,
 82,
 84,
 84,
 84,
 84,
 84,
 85,
 85,
 85,
 86,
 86,
 86,
 86,
 88,
 88,
 88,
 88,
 88,
 88,
 90,
 90,
 90,
 90,
 90,
 92,
 92,
 92,
 92,
 94,
 94,
 95,
 95,
 95,
 95,
 95,
 95,
 95,
 97,
 97,
 97,
 97,
 97,
 100,
 100,
 101,
 101,
 101,
 101,
 101,
 101,
 102,
 102,
 102,
 102,
 102,
 106,
 110,
 110,
 110,
 110,
 110,
 110,
 110,
 110,
 111,
 111,
 111,
 111,
 112,
 112,
 114,
 114,
 114,
 114,
 114,
 114,
 115,
 116,
 116,
 116,
 116,
 116,
 116,
 116,
 116,
 116,
 120,
 121,
 121,
 121,
 123,
 123,
 123,
 123,
 134,
 135,
 140,
 142,
 143,
 145,
 145,
 145,
 145,
 145,
 152,
 152,
 152,
 154,
 155,
 155,
 156,
 156,
 160,
 160,
 160,
 160,
 160,
 161,
 161,
 162,
 162,
 175,
 176,
 176,
 182,
 182,
 182,
 184,
 184,
 200,
 207,
 207,
 207,
 262]

In [14]:
q1 = np.percentile(horsepower,25)

In [15]:
q1

70.0

In [16]:
q3= np.percentile(horsepower,75)

In [17]:
q3

116.0

In [19]:
IQR = q3 - q1

In [30]:
#suspected outliers lies below and above of minhp1 and maxhp1
minhp1 = q1 -(1.5 * IQR) 
maxhp1 = q3 +(1.5 * IQR)

In [31]:
minhp

1.0

In [32]:
maxhp

185.0

In [39]:
#Real outliers lies below and above of minhp2 and maxhp2
minhp2 = q1 -(3 * IQR) 
maxhp2 = q3 +(3 * IQR)

In [40]:
minhp2

-68.0

In [41]:
maxhp2

254.0

In [51]:
outliers=[]
for y in horsepower: 
    if y < minhp1 or y > maxhp1:
        outliers.append(y)
print (outliers)

[200, 207, 207, 207, 262]